# Equal-Weight S&P 500 Index Fund

## What is Algorithmic Trading?

According to [investopedia](https://www.investopedia.com/articles/active-trading/101014/basics-algorithmic-trading-concepts-and-examples.asp) algorithmic trading aka black-box trading uses computer program to follow a defined set of instructions to place a trade. The trade, in theory, can generate profits at a speed and frequency that is impossible for a human trader.

## Why Algorithmic Trading?

In an article by [straitsresearch](https://straitsresearch.com/report/algorithmic-trading-market), the global algorithmic trading market size was valued at USD 35701 million in 2021. It is expected to reach USD 104971.2 million at a compound annual growth rate (CAGR) of 12.73% during the period of 2022-2030.

## Major players:
1. 63MOONS
2. Virtu Financial
3. Software AG
4. Refinitiv Ltd.
5. MetaQuotes Software Corp.

## Algorithmic Trading Process

The process of running a quantitive investing strategy can be broken down into the following steps:

1. Collect Data
2. Develop a hypothesis for a strategy
3. Backtest that strategy
4. Implement the strategy in production

## Aim

The aim of this project is to explore the construction of an index fund that ensures equitable distribution of portfolio funds among selected shares. The objective is to provide users with guidance on the optimal allocation of shares based on their input funds. Furthermore, we envision expanding the dataset to encompass a wider range of company stocks beyond the S&P500 in the future.

## What is an API

API is an Application Programming Interface.

here is some to practice: [github](github.com/public-apis/public-apis)

## What is S&P 500?

S&P500: The Standard and Poor's 500 company

S&P 500 is the world's most popular stock market index. Many investment funds are benchmarked to S&P 500. This means that they seek to replicate the performance of the index by owning all the stocks that are held in the index.

One of the most important characteristics of S&P 500 is that it is market capitalization-weighted. (this means that larger companies get a correspondingly larger weight in the index).

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import math
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
import regex as re

Webscrape list of current companies in S&P 500

In [204]:
def company_details(num):
    company = companies[num].find('a').text.strip() if companies[num].find('a') else None
    
    ticker_tag = companies[num].find_all('a')
    ticker = ticker_tag[1].text.strip() if len(ticker_tag) >= 2 else None
    
    market_tag = companies[num].find_all('a')
    market = market_tag[2].text.strip() if len(market_tag) >= 1 else None
    
    country_tag = companies[num].find_all('a')
    country = country_tag[3].text.strip() if len(country_tag) >= 4 else None

    sector_tag = companies[num].find_all('a')
    sector = sector_tag[4].text.strip() if len(sector_tag) >= 5 else None

    industry_tag = companies[num].find_all('a')
    industry = industry_tag[5].text.strip() if len(industry_tag) >= 6 else None
        
    return {'Company': company,
            'Ticker': ticker,
            'Market_Cap': market,
            'Country': country,
            'Sector': sector,
            'Industry': industry}

In [195]:
url = 'https://disfold.com/stock-index/sp-500/companies/?page='

Continue to webscrape until details of all 500 companies are collected.

In [209]:
headers = {'Accept-Language': 'en-US,en;q=0.9'}
company_lst = []
for x in tqdm(range (1,11)):
    html = requests.get(url+str(x), headers=headers)
    raw = html.text
    soup = BeautifulSoup(raw, 'lxml')
    companies = soup.find_all('tr')

    for i in tqdm(range (len(companies))):
        company_lst.append(company_details(i))

  0%|                                                   | 0/10 [00:00<?, ?it/s]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 3639.90it/s]
 10%|████▎                                      | 1/10 [00:03<00:33,  3.74s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 5663.78it/s]
 20%|████████▌                                  | 2/10 [00:07<00:30,  3.78s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 5097.82it/s]
 30%|████████████▉                              | 3/10 [00:11<00:26,  3.75s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 5663.78it/s]
 40%|█████████████████▏                         | 4/10 [00:14<00:22,  3.74s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 6402.75it/s]
 50%|█████████████████████▌                     | 5/10 [00:18<00:18,  3.75s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 5097.09it/s]
 60%|█████████████████████████▊                 | 6/10 [00:22<00:15,  3.81s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 5646.73it/s]
 70%|██████████████████████████████             | 7/10 [00:26<00:11,  3.76s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 6339.94it/s]
 80%|██████████████████████████████████▍        | 8/10 [00:30<00:07,  3.74s/it]
100%|████████████████████████████████████████| 51/51 [00:00<00:00, 6378.88it/s]
 90%|██████████████████████████████████████▋    | 9/10 [00:33<00:03,  3.72s/it]
100%|████████████████████████████████████████| 48/48 [00:00<00:00, 5985.09it/s]
100%|██████████████████████████████████████████| 10/10 [00:35<00:00,  3.55s/it]

In [210]:
company = pd.DataFrame(company_lst, columns = ['Company','Ticker','Market_Cap','Country','Sector', 'Industry'])

In [211]:
company.head()

,Company,Ticker,Market_Cap,Country,Sector,Industry
0,None,None,None,None,None,None
1,Apple Inc.,AAPL,$2.067 T,United States,Technology,Consumer Electronics
2,Microsoft Corporation,MSFT,$1.788 T,United States,Technology,Software—Infrastructure
3,Alphabet Inc.,GOOG,$1.158 T,United States,Communication Services,Internet Content & Information
4,Alphabet Inc.,GOOGL,$1.158 T,United States,Communication Services,Internet Content & Information

In [230]:
company = company.iloc[1: , :]

In [255]:
company[company['Ticker'].isnull()]

    Company Ticker Market_Cap Country Sector Industry
51     None   None       None    None   None     None
102    None   None       None    None   None     None
153    None   None       None    None   None     None
204    None   None       None    None   None     None
255    None   None       None    None   None     None
306    None   None       None    None   None     None
357    None   None       None    None   None     None
408    None   None       None    None   None     None
459    None   None       None    None   None     None

In [256]:
company.dropna(subset=['Ticker'],inplace=True)

In [257]:
company.to_csv('./dataset/company.csv', index=False)

In [258]:
list(company['Ticker'])

['AAPL',
 'MSFT',
 'GOOG',
 'GOOGL',
 'AMZN',
 'BRK.B',
 'UNH',
 'JNJ',
 'XOM',
 'V',
 'JPM',
 'TSLA',
 'WMT',
 'NVDA',
 'PG',
 'LLY',
 'CVX',
 'MA',
 'HD',
 'META',
 'PFE',
 'ABBV',
 'MRK',
 'KO',
 'BAC',
 'PEP',
 'AVGO',
 'ORCL',
 'TMO',
 'COST',
 'CSCO',
 'MCD',
 'ABT',
 'DHR',
 'NKE',
 'TMUS',
 'ACN',
 'NEE',
 'VZ',
 'DIS',
 'WFC',
 'LIN',
 'PM',
 'ADBE',
 'SCHW',
 'CMCSA',
 'BMY',
 'UPS',
 'TXN',
 'RTX',
 'COP',
 'HON',
 'MS',
 'AMGN',
 'NFLX',
 'CRM',
 'T',
 'UNP',
 'IBM',
 'LMT',
 'DE',
 'CAT',
 'QCOM',
 'CVS',
 'LOW',
 'GS',
 'BA',
 'SBUX',
 'INTC',
 'AXP',
 'INTU',
 'SPGI',
 'PLD',
 'GILD',
 'BLK',
 'MDT',
 'AMD',
 'CI',
 'AMT',
 'ADP',
 'ISRG',
 'GE',
 'SYK',
 'TJX',
 'MDLZ',
 'CB',
 'EL',
 'C',
 'NOC',
 'ADI',
 'MMC',
 'MO',
 'AMAT',
 'PYPL',
 'DUK',
 'REGN',
 'BKNG',
 'NOW',
 'SO',
 'PGR',
 'SLB',
 'VRTX',
 'BDX',
 'EOG',
 'ITW',
 'HCA',
 'TGT',
 'APD',
 'ZTS',
 'GD',
 'MMM',
 'PNC',
 'USB',
 'CL',
 'BSX',
 'CSX',
 'WM',
 'FISV',
 'HUM',
 'ETN',
 'AON',
 'SHW',
 'EQIX',
 'CME',
 'CCI',
 'LRCX',
 'ICE',
 'NSC',
 'OXY',
 'MET',
 'TFC',
 'EMR',
 'DG',
 'MU',
 'FCX',
 'KLAC',
 'MCK',
 'PXD',
 'MNST',
 'ORLY',
 'CHTR',
 'D',
 'MPC',
 'MCO',
 'GIS',
 'KHC',
 'ADM',
 'PSA',
 'PSX',
 'VLO',
 'AEP',
 'SNPS',
 'SRE',
 'GM',
 'MAR',
 'ROP',
 'F',
 'AIG',
 'HSY',
 'KMB',
 'EW',
 'AZO',
 'CTAS',
 'APH',
 'AFL',
 'CNC',
 'FDX',
 'A',
 'DXCM',
 'SPG',
 'JCI',
 'TRV',
 'CDNS',
 'HES',
 'MSI',
 'EXC',
 'STZ',
 'CTVA',
 'ECL',
 'PAYX',
 'ROST',
 'RSG',
 'NEM',
 'O',
 'FIS',
 'KMI',
 'DVN',
 'WMB',
 'ADSK',
 'AJG',
 'LHX',
 'BIIB',
 'SYY',
 'TT',
 'XEL',
 'CMG',
 'MCHP',
 'FTNT',
 'IQV',
 'PH',
 'BK',
 'PRU',
 'MSCI',
 'LVS',
 'TEL',
 'ALL',
 'YUM',
 'DOW',
 'HAL',
 'DD',
 'COF',
 'NUE',
 'PCAR',
 'CARR',
 'ENPH',
 'TDG',
 'HLT',
 'EA',
 'CMI',
 'ED',
 'ANET',
 'IDXX',
 'ABC',
 'OTIS',
 'AMP',
 'MTD',
 'WBA',
 'AME',
 'KR',
 'ODFL',
 'ILMN',
 'BF.B',
 'RMD',
 'PEG',
 'DHI',
 'DLTR',
 'WELL',
 'NDAQ',
 'KEYS',
 'PPG',
 'SBAC',
 'DLR',
 'ROK',
 'CTSH',
 'WEC',
 'OKE',
 'ES',
 'CPRT',
 'BKR',
 'WLTW',
 'STT',
 'GWW',
 'AWK',
 'VRSK',
 'GLW',
 'FAST',
 'GPN',
 'LYB',
 'IFF',
 'LEN',
 'ZBH',
 'DFS',
 'IT',
 'KSU',
 'HPQ',
 'BAX',
 'MTB',
 'APTV',
 'ALB',
 'HRL',
 'TSCO',
 'CBRE',
 'URI',
 'EIX',
 'GPC',
 'TROW',
 'K',
 'CDW',
 'HIG',
 'FE',
 'FANG',
 'ULTA',
 'EFX',
 'ARE',
 'VMC',
 'EQR',
 'RJF',
 'ETR',
 'AEE',
 'EBAY',
 'DTE',
 'FTV',
 'AVB',
 'DAL',
 'FITB',
 'MKC',
 'WY',
 'FRC',
 'TSN',
 'PPL',
 'VRSN',
 'IR',
 'MLM',
 'LH',
 'LB',
 'HPE',
 'ANSS',
 'PFG',
 'EXR',
 'RF',
 'WAT',
 'UDR',
 'PWR',
 'HBAN',
 'CAH',
 'CHD',
 'LUV',
 'XYL',
 'CAG',
 'WRB',
 'NTRS',
 'HOLX',
 'CFG',
 'DOV',
 'DRE',
 'STE',
 'VTR',
 'TDY',
 'WAB',
 'CMS',
 'GRMN',
 'CNP',
 'MAA',
 'BBY',
 'PAYC',
 'ROL',
 'AMCR',
 'INCY',
 'TTWO',
 'DRI',
 'DGX',
 'JBHT',
 'PKI',
 'CLX',
 'OMC',
 'AES',
 'WST',
 'ALGN',
 'ABMD',
 'IEX',
 'SJM',
 'CPB',
 'CINF',
 'COO',
 'EXPD',
 'KEY',
 'LYV',
 'CF',
 'MRO',
 'FOXA',
 'FOX',
 'HWM',
 'BALL',
 'BR',
 'J',
 'ATO',
 'FMC',
 'EXPE',
 'ETSY',
 'MOS',
 'AVY',
 'NVR',
 'SWKS',
 'TXT',
 'LKQ',
 'EVRG',
 'NLOK',
 'SYF',
 'VTRS',
 'IRM',
 'LDOS',
 'ESS',
 'LW',
 'L',
 'PEAK',
 'ZBRA',
 'PARA',
 'SIVB',
 'IPG',
 'BEN',
 'RCL',
 'LNT',
 'TER',
 'MGM',
 'NTAP',
 'APA',
 'RE',
 'AKAM',
 'FLT',
 'CBOE',
 'CTXS',
 'KIM',
 'UAL',
 'IP',
 'TYL',
 'BIO',
 'JKHY',
 'DISCA',
 'DISCK',
 'SNA',
 'CE',
 'PKG',
 'DPZ',
 'TFX',
 'POOL',
 'GL',
 'CCL',
 'SWK',
 'HST',
 'VFC',
 'HSIC',
 'MKTX',
 'WDC',
 'STX',
 'NI',
 'PHM',
 'NWS',
 'NWSA',
 'TAP',
 'REG',
 'UHS',
 'CHRW',
 'MAS',
 'WYNN',
 'EMN',
 'JNPR',
 'NLSN',
 'BXP',
 'KMX',
 'BWA',
 'ALLE',
 'TPR',
 'QRVO',
 'AAP',
 'AAL',
 'HII',
 'WRK',
 'AOS',
 'HAS',
 'CMA',
 'FFIV',
 'PBCT',
 'FRT',
 'PNW',
 'CTLT',
 'IVZ',
 'WHR',
 'UNM',
 'RHI',
 'NOV',
 'DISH',
 'FBHS',
 'PNR',
 'RL',
 'SEE',
 'ZION',
 'NRG',
 'XRAY',
 'DVA',
 'MHK',
 'FLIR',
 'AIZ',
 'DXC',
 'HFC',
 'NWL',
 'LUMN',
 'ALK',
 'NCLH',
 'WU',
 'LNC',
 'FTI',
 'PVH',
 'IPGP',
 'PRGO',
 'UA',
 'UAA',
 'LEG',
 'VNO',
 'GPS',
 'FLS',
 'ANTM',
 'VNT',
 'HBI',
 'XRX',
 'SLG',
 'COG',
 'VAR']

In [2]:
company = pd.read_csv('./dataset/company.csv')

In [3]:
company.head()

,Company,Ticker,Market_Cap,Country,Sector,Industry
0,Apple Inc.,AAPL,$2.067 T,United States,Technology,Consumer Electronics
1,Microsoft Corporation,MSFT,$1.788 T,United States,Technology,Software—Infrastructure
2,Alphabet Inc.,GOOG,$1.158 T,United States,Communication Services,Internet Content & Information
3,Alphabet Inc.,GOOGL,$1.158 T,United States,Communication Services,Internet Content & Information
4,"Amazon.com, Inc.",AMZN,$875.51 B,United States,Consumer Discretionary,Internet Retail

Observations:

It is oberved that the column 'Market_Cap' have '$' and 'T' with integers. The next few steps are to remove the dollar signs and input the correct amount of 'zeros' to trillions and billions.

In [4]:
company.shape

(497, 6)

In [5]:
company[company['Market_Cap'] == 'United States']

,Company,Ticker,Market_Cap,Country,Sector,Industry
263,Kansas City Southern,KSU,United States,Industrials,Railroads,NaN
322,"Citizens Financial Group, Inc.",CFG,United States,Financials,Banks,NaN
324,Duke Realty Corporation,DRE,United States,Real Estate,REIT—Industrial,NaN
348,"Abiomed, Inc.",ABMD,United States,Healthcare,Medical Devices,NaN
400,"Citrix Systems, Inc.",CTXS,United States,Technology,Software—Application,NaN
436,Nielsen Holdings plc,NLSN,United States,Industrials,Consulting Services,NaN
451,"People's United Financial, Inc.",PBCT,United States,Financials,Banks,NaN
470,"FLIR Systems, Inc.",FLIR,United States,Technology,Scientific & Technical Instruments,NaN
473,HollyFrontier Corporation,HFC,United States,Energy,Oil & Gas Refining & Marketing,NaN

In [6]:
company.loc[company['Company'] == 'Kansas City Southern', 'Market_Cap'] = company.loc[company['Company'] == 'Kansas City Southern', 'Market_Cap'] = '$26.59 B'

In [7]:
company.loc[company['Company'] == 'Citizens Financial Group, Inc.', 'Market_Cap'] = company.loc[company['Company'] == 'Citizens Financial Group, Inc.', 'Market_Cap'] = '$18.95 B'

In [8]:
company.loc[company['Company'] == 'Duke Realty Corporation', 'Market_Cap'] = company.loc[company['Company'] == 'Duke Realty Corporation', 'Market_Cap'] = '$18.74 B'

In [9]:
company.loc[company['Company'] == 'Abiomed, Inc.', 'Market_Cap'] = company.loc[company['Company'] == 'Abiomed, Inc.', 'Market_Cap'] = '$17.18 B'

In [10]:
company.loc[company['Company'] == 'Citrix Systems, Inc.', 'Market_Cap'] = company.loc[company['Company'] == 'Citrix Systems, Inc.', 'Market_Cap'] = '$13.18 B'

In [11]:
company.loc[company['Company'] == 'Nielsen Holdings plc', 'Market_Cap'] = company.loc[company['Company'] == 'Nielsen Holdings plc', 'Market_Cap'] = '$10.06 B'

In [12]:
company.loc[company['Company'] == "People's United Financial, Inc.", 'Market_Cap'] = company.loc[company['Company'] == "People's United Financial, Inc.", 'Market_Cap'] = '$8.45 B'

In [13]:
company.loc[company['Company'] == 'FLIR Systems, Inc.', 'Market_Cap'] = company.loc[company['Company'] == 'FLIR Systems, Inc.', 'Market_Cap'] = '$6.83 B'

In [14]:
company.loc[company['Company'] == 'HollyFrontier Corporation', 'Market_Cap'] = company.loc[company['Company'] == 'HollyFrontier Corporation', 'Market_Cap'] = '$5.91 B'

In [15]:
company[company['Market_Cap'] == 'United States']

Empty DataFrame
Columns: [Company, Ticker, Market_Cap, Country, Sector, Industry]
Index: []

Convert market cap prices to integers

In [16]:
company['Market_Cap'] = company['Market_Cap'].map(lambda x:x.replace('$',''))

In [17]:
company['Market_Cap'][0][-1:]

'T'

In [18]:
company['Amount'] = company['Market_Cap'].map(lambda x:x[-1:])

In [19]:
company['Amount'] = company['Amount'].map(lambda x:1000000000000 if x == 'T' else (1000000000 if x =='B' else 1000000 ))

In [20]:
company.head()

,Company,Ticker,Market_Cap,Country,Sector,Industry,Amount
0,Apple Inc.,AAPL,2.067 T,United States,Technology,Consumer Electronics,1000000000000
1,Microsoft Corporation,MSFT,1.788 T,United States,Technology,Software—Infrastructure,1000000000000
2,Alphabet Inc.,GOOG,1.158 T,United States,Communication Services,Internet Content & Information,1000000000000
3,Alphabet Inc.,GOOGL,1.158 T,United States,Communication Services,Internet Content & Information,1000000000000
4,"Amazon.com, Inc.",AMZN,875.51 B,United States,Consumer Discretionary,Internet Retail,1000000000

In [21]:
company['Market_Cap'] = company['Market_Cap'].map(lambda x:x[:-2])

In [22]:
company['Market_Cap'] = company['Market_Cap'].map(lambda x:float(x))

In [23]:
company.head()

,Company,Ticker,Market_Cap,Country,Sector,Industry,Amount
0,Apple Inc.,AAPL,2.067,United States,Technology,Consumer Electronics,1000000000000
1,Microsoft Corporation,MSFT,1.788,United States,Technology,Software—Infrastructure,1000000000000
2,Alphabet Inc.,GOOG,1.158,United States,Communication Services,Internet Content & Information,1000000000000
3,Alphabet Inc.,GOOGL,1.158,United States,Communication Services,Internet Content & Information,1000000000000
4,"Amazon.com, Inc.",AMZN,875.510,United States,Consumer Discretionary,Internet Retail,1000000000

In [24]:
company['Market'] = company['Market_Cap'] * company['Amount']

In [25]:
company.drop(columns = ['Market_Cap', 'Amount'],inplace=True)

In [26]:
company.head(10)

,Company,Ticker,Country,Sector,Industry,Market
0,Apple Inc.,AAPL,United States,Technology,Consumer Electronics,2.067000e+12
1,Microsoft Corporation,MSFT,United States,Technology,Software—Infrastructure,1.788000e+12
2,Alphabet Inc.,GOOG,United States,Communication Services,Internet Content & Information,1.158000e+12
3,Alphabet Inc.,GOOGL,United States,Communication Services,Internet Content & Information,1.158000e+12
4,"Amazon.com, Inc.",AMZN,United States,Consumer Discretionary,Internet Retail,8.755100e+11
5,Berkshire Hathaway Inc.,BRK.B,United States,Financials,Financial Conglomerates,6.831000e+11
6,UnitedHealth Group Incorporated,UNH,United States,Healthcare,Healthcare Plans,4.953700e+11
7,Johnson & Johnson,JNJ,United States,Healthcare,Drug Manufacturers—General,4.618500e+11
8,Exxon Mobil Corporation,XOM,United States,Energy,Oil & Gas Integrated,4.542500e+11
9,Visa Inc.,V,United States,Financials,Credit Services,4.399600e+11

In [27]:
company['Stocks'] = None

In [28]:
company_name = list(company['Ticker'].unique())

In [29]:
company_name

['AAPL',
 'MSFT',
 'GOOG',
 'GOOGL',
 'AMZN',
 'BRK.B',
 'UNH',
 'JNJ',
 'XOM',
 'V',
 'JPM',
 'TSLA',
 'WMT',
 'NVDA',
 'PG',
 'LLY',
 'CVX',
 'MA',
 'HD',
 'META',
 'PFE',
 'ABBV',
 'MRK',
 'KO',
 'BAC',
 'PEP',
 'AVGO',
 'ORCL',
 'TMO',
 'COST',
 'CSCO',
 'MCD',
 'ABT',
 'DHR',
 'NKE',
 'TMUS',
 'ACN',
 'NEE',
 'VZ',
 'DIS',
 'WFC',
 'LIN',
 'PM',
 'ADBE',
 'SCHW',
 'CMCSA',
 'BMY',
 'UPS',
 'TXN',
 'RTX',
 'COP',
 'HON',
 'MS',
 'AMGN',
 'NFLX',
 'CRM',
 'T',
 'UNP',
 'IBM',
 'LMT',
 'DE',
 'CAT',
 'QCOM',
 'CVS',
 'LOW',
 'GS',
 'BA',
 'SBUX',
 'INTC',
 'AXP',
 'INTU',
 'SPGI',
 'PLD',
 'GILD',
 'BLK',
 'MDT',
 'AMD',
 'CI',
 'AMT',
 'ADP',
 'ISRG',
 'GE',
 'SYK',
 'TJX',
 'MDLZ',
 'CB',
 'EL',
 'C',
 'NOC',
 'ADI',
 'MMC',
 'MO',
 'AMAT',
 'PYPL',
 'DUK',
 'REGN',
 'BKNG',
 'NOW',
 'SO',
 'PGR',
 'SLB',
 'VRTX',
 'BDX',
 'EOG',
 'ITW',
 'HCA',
 'TGT',
 'APD',
 'ZTS',
 'GD',
 'MMM',
 'PNC',
 'USB',
 'CL',
 'BSX',
 'CSX',
 'WM',
 'FISV',
 'HUM',
 'ETN',
 'AON',
 'SHW',
 'EQIX',
 'CME',
 'CCI',
 'LRCX',
 'ICE',
 'NSC',
 'OXY',
 'MET',
 'TFC',
 'EMR',
 'DG',
 'MU',
 'FCX',
 'KLAC',
 'MCK',
 'PXD',
 'MNST',
 'ORLY',
 'CHTR',
 'D',
 'MPC',
 'MCO',
 'GIS',
 'KHC',
 'ADM',
 'PSA',
 'PSX',
 'VLO',
 'AEP',
 'SNPS',
 'SRE',
 'GM',
 'MAR',
 'ROP',
 'F',
 'AIG',
 'HSY',
 'KMB',
 'EW',
 'AZO',
 'CTAS',
 'APH',
 'AFL',
 'CNC',
 'FDX',
 'A',
 'DXCM',
 'SPG',
 'JCI',
 'TRV',
 'CDNS',
 'HES',
 'MSI',
 'EXC',
 'STZ',
 'CTVA',
 'ECL',
 'PAYX',
 'ROST',
 'RSG',
 'NEM',
 'O',
 'FIS',
 'KMI',
 'DVN',
 'WMB',
 'ADSK',
 'AJG',
 'LHX',
 'BIIB',
 'SYY',
 'TT',
 'XEL',
 'CMG',
 'MCHP',
 'FTNT',
 'IQV',
 'PH',
 'BK',
 'PRU',
 'MSCI',
 'LVS',
 'TEL',
 'ALL',
 'YUM',
 'DOW',
 'HAL',
 'DD',
 'COF',
 'NUE',
 'PCAR',
 'CARR',
 'ENPH',
 'TDG',
 'HLT',
 'EA',
 'CMI',
 'ED',
 'ANET',
 'IDXX',
 'ABC',
 'OTIS',
 'AMP',
 'MTD',
 'WBA',
 'AME',
 'KR',
 'ODFL',
 'ILMN',
 'BF.B',
 'RMD',
 'PEG',
 'DHI',
 'DLTR',
 'WELL',
 'NDAQ',
 'KEYS',
 'PPG',
 'SBAC',
 'DLR',
 'ROK',
 'CTSH',
 'WEC',
 'OKE',
 'ES',
 'CPRT',
 'BKR',
 'WLTW',
 'STT',
 'GWW',
 'AWK',
 'VRSK',
 'GLW',
 'FAST',
 'GPN',
 'LYB',
 'IFF',
 'LEN',
 'ZBH',
 'DFS',
 'IT',
 'KSU',
 'HPQ',
 'BAX',
 'MTB',
 'APTV',
 'ALB',
 'HRL',
 'TSCO',
 'CBRE',
 'URI',
 'EIX',
 'GPC',
 'TROW',
 'K',
 'CDW',
 'HIG',
 'FE',
 'FANG',
 'ULTA',
 'EFX',
 'ARE',
 'VMC',
 'EQR',
 'RJF',
 'ETR',
 'AEE',
 'EBAY',
 'DTE',
 'FTV',
 'AVB',
 'DAL',
 'FITB',
 'MKC',
 'WY',
 'FRC',
 'TSN',
 'PPL',
 'VRSN',
 'IR',
 'MLM',
 'LH',
 'LB',
 'HPE',
 'ANSS',
 'PFG',
 'EXR',
 'RF',
 'WAT',
 'UDR',
 'PWR',
 'HBAN',
 'CAH',
 'CHD',
 'LUV',
 'XYL',
 'CAG',
 'WRB',
 'NTRS',
 'HOLX',
 'CFG',
 'DOV',
 'DRE',
 'STE',
 'VTR',
 'TDY',
 'WAB',
 'CMS',
 'GRMN',
 'CNP',
 'MAA',
 'BBY',
 'PAYC',
 'ROL',
 'AMCR',
 'INCY',
 'TTWO',
 'DRI',
 'DGX',
 'JBHT',
 'PKI',
 'CLX',
 'OMC',
 'AES',
 'WST',
 'ALGN',
 'ABMD',
 'IEX',
 'SJM',
 'CPB',
 'CINF',
 'COO',
 'EXPD',
 'KEY',
 'LYV',
 'CF',
 'MRO',
 'FOXA',
 'FOX',
 'HWM',
 'BALL',
 'BR',
 'J',
 'ATO',
 'FMC',
 'EXPE',
 'ETSY',
 'MOS',
 'AVY',
 'NVR',
 'SWKS',
 'TXT',
 'LKQ',
 'EVRG',
 'NLOK',
 'SYF',
 'VTRS',
 'IRM',
 'LDOS',
 'ESS',
 'LW',
 'L',
 'PEAK',
 'ZBRA',
 'PARA',
 'SIVB',
 'IPG',
 'BEN',
 'RCL',
 'LNT',
 'TER',
 'MGM',
 'NTAP',
 'APA',
 'RE',
 'AKAM',
 'FLT',
 'CBOE',
 'CTXS',
 'KIM',
 'UAL',
 'IP',
 'TYL',
 'BIO',
 'JKHY',
 'DISCA',
 'DISCK',
 'SNA',
 'CE',
 'PKG',
 'DPZ',
 'TFX',
 'POOL',
 'GL',
 'CCL',
 'SWK',
 'HST',
 'VFC',
 'HSIC',
 'MKTX',
 'WDC',
 'STX',
 'NI',
 'PHM',
 'NWS',
 'NWSA',
 'TAP',
 'REG',
 'UHS',
 'CHRW',
 'MAS',
 'WYNN',
 'EMN',
 'JNPR',
 'NLSN',
 'BXP',
 'KMX',
 'BWA',
 'ALLE',
 'TPR',
 'QRVO',
 'AAP',
 'AAL',
 'HII',
 'WRK',
 'AOS',
 'HAS',
 'CMA',
 'FFIV',
 'PBCT',
 'FRT',
 'PNW',
 'CTLT',
 'IVZ',
 'WHR',
 'UNM',
 'RHI',
 'NOV',
 'DISH',
 'FBHS',
 'PNR',
 'RL',
 'SEE',
 'ZION',
 'NRG',
 'XRAY',
 'DVA',
 'MHK',
 'FLIR',
 'AIZ',
 'DXC',
 'HFC',
 'NWL',
 'LUMN',
 'ALK',
 'NCLH',
 'WU',
 'LNC',
 'FTI',
 'PVH',
 'IPGP',
 'PRGO',
 'UA',
 'UAA',
 'LEG',
 'VNO',
 'GPS',
 'FLS',
 'ANTM',
 'VNT',
 'HBI',
 'XRX',
 'SLG',
 'COG',
 'VAR']

In [30]:
len(company_name)

497

In [31]:
company.head()

,Company,Ticker,Country,Sector,Industry,Market,Stocks
0,Apple Inc.,AAPL,United States,Technology,Consumer Electronics,2.067000e+12,None
1,Microsoft Corporation,MSFT,United States,Technology,Software—Infrastructure,1.788000e+12,None
2,Alphabet Inc.,GOOG,United States,Communication Services,Internet Content & Information,1.158000e+12,None
3,Alphabet Inc.,GOOGL,United States,Communication Services,Internet Content & Information,1.158000e+12,None
4,"Amazon.com, Inc.",AMZN,United States,Consumer Discretionary,Internet Retail,8.755100e+11,None

After cleaning the data, webscraping is needed to input what is the stock price for a company.

In [32]:
for i in tqdm(range(len(company_name))):
    # Define the ticker symbol
    ticker_symbol = company_name[i] 

    try:
        # Retrieve the stock data
        stock_data = yf.Ticker(ticker_symbol)

        # Try different keys to get the current stock price
        price_keys = ["regularMarketPrice", "currentPrice", "ask"]
        current_price = None

        for key in price_keys:
            if key in stock_data.info:
                current_price = stock_data.info[key]
                break

        if current_price is not None:
            company.loc[company['Ticker'] == company_name[i], 'Stocks'] = current_price
        else:
            company.loc[company['Ticker'] == company_name[i], 'Stocks'] = None

    except Exception as e:
        print(f"Failed to retrieve stock data for {ticker_symbol}: {str(e)}")
        company.loc[company['Ticker'] == company_name[i], 'Stocks'] = None

 45%|█████████████████▉                      | 223/497 [06:53<35:25,  7.76s/it]

Failed to retrieve stock data for ABC: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

 50%|████████████████████                    | 250/497 [07:45<06:15,  1.52s/it]

Failed to retrieve stock data for WLTW: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/WLTW?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 53%|█████████████████████▏                  | 264/497 [08:09<05:47,  1.49s/it]

Failed to retrieve stock data for KSU: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/KSU?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 61%|████████████████████████▌               | 305/497 [09:30<04:43,  1.47s/it]

Failed to retrieve stock data for LB: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/LB?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 65%|██████████████████████████▏             | 325/497 [10:04<04:07,  1.44s/it]

Failed to retrieve stock data for DRE: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/DRE?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 76%|██████████████████████████████▎         | 377/497 [11:44<03:04,  1.53s/it]

Failed to retrieve stock data for NLOK: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/NLOK?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 78%|███████████████████████████████▏        | 388/497 [12:03<02:36,  1.43s/it]

Failed to retrieve stock data for SIVB: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/SIVB?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 82%|████████████████████████████████▊       | 408/497 [12:47<02:48,  1.89s/it]

Failed to retrieve stock data for DISCA: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/DISCA?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 82%|████████████████████████████████▉       | 409/497 [12:50<03:13,  2.20s/it]

Failed to retrieve stock data for DISCK: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/DISCK?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 88%|███████████████████████████████████▏    | 437/497 [13:36<01:16,  1.28s/it]

Failed to retrieve stock data for NLSN: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/NLSN?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 91%|████████████████████████████████████▍   | 452/497 [14:00<00:58,  1.30s/it]

Failed to retrieve stock data for PBCT: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/PBCT?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 93%|█████████████████████████████████████▏  | 462/497 [14:17<00:52,  1.49s/it]

Failed to retrieve stock data for FBHS: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/FBHS?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 95%|█████████████████████████████████████▉  | 471/497 [14:32<00:36,  1.40s/it]

Failed to retrieve stock data for FLIR: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/FLIR?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 95%|██████████████████████████████████████▏ | 474/497 [14:35<00:29,  1.26s/it]

Failed to retrieve stock data for HFC: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/HFC?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

 99%|███████████████████████████████████████▌| 491/497 [15:07<00:07,  1.32s/it]

Failed to retrieve stock data for ANTM: 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/ANTM?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

100%|████████████████████████████████████████| 497/497 [15:16<00:00,  1.84s/it]

In [33]:
company.head()

,Company,Ticker,Country,Sector,Industry,Market,Stocks
0,Apple Inc.,AAPL,United States,Technology,Consumer Electronics,2.067000e+12,189.59
1,Microsoft Corporation,MSFT,United States,Technology,Software—Infrastructure,1.788000e+12,335.05
2,Alphabet Inc.,GOOG,United States,Communication Services,Internet Content & Information,1.158000e+12,120.01
3,Alphabet Inc.,GOOGL,United States,Communication Services,Internet Content & Information,1.158000e+12,119.1
4,"Amazon.com, Inc.",AMZN,United States,Consumer Discretionary,Internet Retail,8.755100e+11,127.9

In [34]:
company['Stocks'].unique()

array([189.59, 335.05, 120.01, 119.1, 127.9, None, 476.44, 164.1, 106.7,
       234.32, 143.43, 257.5, 154.28, 408.22, 149.38, 464.49, 156.24,
       387.67, 307.82, 281.53, 36.12, 133.23, 113.54, 60.02, 28.66,
       183.88, 862.57, 117.78, 514.39, 531.69, 51.21, 294.47, 107.66,
       237.77, 113.37, 136.84, 308.33, 72.81, 36.99, 88.95, 42.45, 379.19,
       97.69, 483.77, 57.14, 41.47, 64.0, 176.05, 176.79, 97.8, 103.06,
       206.47, 85.24, 221.16, 428.24, 210.43, 15.98, 204.65, 134.06,
       457.44, 401.63, 244.24, 118.06, 68.76, 222.82, 323.09, 211.83,
       98.68, 32.91, 172.08, 455.82, 395.84, 121.5, 76.01, 688.21, 86.77,
       111.24, 277.25, 192.73, 216.46, 338.49, 107.74, 301.77, 83.74,
       72.28, 189.1, 192.53, 46.29, 451.22, 189.48, 185.93, 44.97, 144.23,
       65.86, 88.88, 708.42, 2655.91, 548.08, 69.14, 132.07, 48.47,
       348.18, 260.52, 113.0, 248.51, 300.44, 132.91, 294.75, 171.87,
       214.31, 99.24, 125.68, 32.76, 76.56, 53.29, 33.87, 169.61, 114.23,
       443.86, 198.85, 342.12, 261.29, 777.03, 183.36, 114.08, 640.36,
       112.28, 225.98, 58.52, 56.18, 30.64, 89.22, 166.77, 64.33, 39.35,
       477.23, 420.88, 206.07, 57.42, 937.42, 362.68, 51.82, 116.34,
       344.45, 76.3, 35.02, 74.62, 288.59, 94.53, 116.61, 83.26, 427.9,
       144.89, 38.2, 181.27, 476.13, 14.95, 57.2, 248.68, 137.16, 92.02,
       2455.4, 490.03, 83.45, 69.12, 66.99, 249.98, 118.05, 127.94,
       114.76, 67.32, 170.99, 228.54, 133.86, 40.11, 246.85, 57.7, 109.33,
       108.87, 151.44, 41.95, 60.22, 52.92, 17.2, 48.4, 32.53, 206.18,
       214.67, 195.49, 282.13, 73.13, 189.99, 61.29, 2110.6, 86.98, 75.09,
       221.42, 386.75, 44.2, 87.84, 462.07, 57.38, 138.39, 109.09, 137.26,
       53.24, 33.19, 70.86, 109.26, 163.33, 82.61, 49.49, 158.77, 886.12,
       143.92, 130.45, 242.0, 89.57, 159.29, 494.49, 88.61, 331.59,
       1316.88, 28.37, 160.14, 46.32, 375.75, 185.49, 216.23, 61.84,
       120.34, 143.61, 80.39, 49.85, 165.34, 145.37, 229.68, 111.88,
       324.24, 64.54, 87.25, 61.49, 69.72, 90.26, 31.36, 73.14, 782.3,
       140.47, 223.27, 34.71, 58.54, 96.97, 90.66, 77.81, 123.78, 145.15,
       117.9, 342.54, 30.32, 44.7, 124.21, 100.89, 218.98, 39.86, 217.42,
       80.3, 435.63, 68.57, 166.06, 111.18, 66.82, 180.65, 71.33, 38.61,
       130.01, 465.28, 234.44, 224.84, 65.42, 103.66, 95.73, 80.99, 44.6,
       109.25, 73.54, 188.04, 46.31, 26.25, 86.78, 33.33, 3.51, 50.69,
       26.18, 222.93, 64.4, 457.83, 240.48, 16.65, 326.05, 75.61, 147.97,
       17.69, 261.95, 42.88, 194.85, 10.79, 93.92, 98.97, 35.95, 111.34,
       33.31, 59.12, 73.35, 80.07, 25.93, 144.65, 220.99, 47.62, 407.28,
       108.01, 58.41, 103.6, 28.72, 152.07, 83.21, 313.68, 42.5, 9.9,
       61.85, 145.47, 165.3, 141.14, 182.47, 115.24, 157.91, 94.13, 20.43,
       377.36, 341.79, 381.02, 213.53, 146.37, 45.48, 96.64, 379.98,
       120.14, 9.33, 89.68, 70.32, 22.93, 34.41, 32.11, 48.76, 57.71,
       163.3, 118.26, 115.7, 104.53, 107.84, 85.73, 34.78, 167.99,
       6295.61, 109.88, 67.33, 57.56, 34.07, 9.91, 56.16, 87.78, 233.07,
       113.89, 59.11, 19.98, 288.68, 15.99, 38.09, 26.8, 101.56, 51.79,
       109.4, 43.01, 76.15, 33.92, 339.66, 89.19, 248.05, 135.76, 19.7,
       53.72, 31.68, 411.73, 375.24, 166.48, 286.96, 114.12, 131.86,
       330.73, 234.95, 370.62, 108.95, 17.16, 94.61, 16.69, 19.2, 80.9,
       261.98, 37.6, 61.94, 27.17, 77.32, 19.74, 19.53, 65.62, 61.68,
       156.51, 94.28, 57.34, 104.5, 82.91, 30.88, 57.1, 84.34, 48.19,
       119.58, 42.83, 101.34, 68.23, 17.6, 226.96, 28.68, 72.38, 63.83,
       42.85, 145.77, 96.35, 80.73, 43.04, 16.75, 149.46, 47.45, 74.07,
       15.96, 6.69, 63.68, 123.11, 27.28, 37.17, 39.51, 98.83, 103.43,
       124.52, 26.23, 8.96, 2.2, 52.27, 20.9, 11.62, 25.49, 16.32, 83.63,
       134.36, 33.64, 6.63, 7.14, 29.87, 17.22, 8.82, 36.88, 31.92, 4.5,
       14.85, 28.88], dtype=object)

Calculate the number of shares to buy based on input portfolio

In [62]:
indicator = True
while indicator == True:
    portfolio_size = input('Enter the value of your portfolio: ')
    try:
        value = float(portfolio_size)
        indicator = False

    except ValueError:
        print('That is not a number! \n Please try again.')

Enter the value of your portfolio:  10000000

Calculating the amount of money to be invested in each company.

In [63]:
company['Stocks'] = company['Stocks'].dropna()

In [64]:
company['Stocks'] = company['Stocks'].fillna(0)

In [65]:
position_size = value/len(company['Market'].index)
company['Portfolio_Shares'] = company['Stocks'].apply(lambda x: math.floor(position_size / x) if x != 0 else 0)

In [66]:
company.head()

,Company,Ticker,Country,Sector,Industry,Market,Stocks,Portfolio_Shares
0,Apple Inc.,AAPL,United States,Technology,Consumer Electronics,2.067000e+12,189.59,106
1,Microsoft Corporation,MSFT,United States,Technology,Software—Infrastructure,1.788000e+12,335.05,60
2,Alphabet Inc.,GOOG,United States,Communication Services,Internet Content & Information,1.158000e+12,120.01,167
3,Alphabet Inc.,GOOGL,United States,Communication Services,Internet Content & Information,1.158000e+12,119.10,168
4,"Amazon.com, Inc.",AMZN,United States,Consumer Discretionary,Internet Retail,8.755100e+11,127.90,157

In [68]:
company.shape

(497, 8)

In [67]:
company.to_csv('./dataset/recommended_trades.csv', index=False)

This shows the amount of shares one can buy with 10 million dollars of equal weight in each shares, in the given the list of S&P 500. Do note that this list can be modified to accomodate other stocks.